### ISSUE TITLE
porting.mk error?

### ISSUE THREAD

**Issue by 1982Strand** [MiCode/patchrom_build#3]
Today (friday, june 8) i made a "repo sync" and tried to build, like i usually do..
But i get this error now:

_<<< install framework resources completed!
unzip >/dev/null Beta_0.8.1.zip system/framework/services.jar -d out
/root/patchrom/tools/apktool --quiet d -f out/system/framework/services.jar services.jar.out
unzip >/dev/null Beta_0.8.1.zip system/framework/android.policy.jar -d out
/root/patchrom/tools/apktool --quiet d -f out/system/framework/android.policy.jar android.policy.jar.out
unzip >/dev/null Beta_0.8.1.zip system/framework/framework.jar -d out
/root/patchrom/tools/apktool --quiet d -f out/system/framework/framework.jar framework.jar.out_

**if unzip >/dev/null Beta_0.8.1.zip system/framework/framework-res.apk -d out >/dev/null; then /root/patchrom/tools/apktool --quiet d -f out/system/framework/framework-res.apk framework-res ; else echo system/framework/framework-res.apk does not exist, ignored!;  fi**

_fix the apktool multiple position substitution bug
/root/patchrom/tools/fix_plurals.sh >/dev/null framework-res
Prepare workspace completed!_

Beta_0.8.1.zip is my base rom zip.
patchrom is installed to root/patchrom

How can i fix this?

**Comment by fanoge** [comment]
where is the error?

**Comment by 1982Strand** [comment]
Ok, finally found out this isn't really an error. Just got confused by the message thrown by patchrom..
